---
# 0 = off
# 1 = warn
# 2 = error

extends: standard
rules:
  strict: [1, 'safe']
  block-scoped-var: 2
  complexity: 1
  default-case: 2
  dot-notation: 1
  guard-for-in: 1
  linebreak-style: [2, 'unix']
  no-alert: 2
  no-case-declarations: 2
  no-console: 1
  no-constant-condition: 2
  no-continue: 1
  no-div-regex: 2
  no-empty: 1
  no-empty-pattern: 2
  no-extra-semi: 2
  no-implicit-coercion: 2
  no-labels: 2
  no-loop-func: 2
  no-nested-ternary: 2
  no-script-url: 2
  no-unused-vars:
    - 2
    - "varsIgnorePattern":
        "^(contractItOnly|d)$"
  no-warning-comments: 1
  quote-props: [2, 'as-needed']
  require-yield: 2
